name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and push topng Docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./topng
          push: true
          tags: stelzo/svg-to-png:latest
      - name: Build and push tosvg Docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: ./tosvg
          push: true
          tags: stelzo/swf-to-svg:latest
